homeassistant:
  name: Home
  latitude: !secret lat_home
  longitude: !secret long_home
  elevation: 0
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

default_config:

homekit:
  filter:
    include_domains:
      - switch
      - light
      - script
      - media_player
      - groups
  entity_config:
    media_player.samsung_tv_remote:
      feature_list:
        - feature: on_off
        - feature: play_pause
    media_player.home_tv:
      feature_list:
        - feature: on_off

device_tracker:
  - platform: bluetooth_tracker
    consider_home: 200
    new_device_defaults:
      track_new_devices: false
      hide_if_away: false

http:
  base_url: !secret https
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret conf_https

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

counter:
  night_mode:
    initial: 0
    step: 1
    minimum: 0
    maximum: 1
circadian_lighting:
  max_colortemp: 5000 
  min_colortemp: 2857
  interval: 600
  transition: 3
switch: !include switches.yaml

api:

frontend:
  themes: !include themes.yaml
zone: !include zones.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml




